### ISSUE TITLE
Automatic ammo pick up doesn't work for me

### ISSUE THREAD

**Issue by clearedgee** [tominator1pl/bl-sdk-mods#3]
Only works for money and eridium. But still helps a lot, thank you for this mod nonetheless!

**Comment by 1basti1** [comment]
I think for me it only picks up eridium, nothing more.

**Comment by PoorPocketsMcNewHold** [comment]
It only picks health for me. Not even money or else. It's a bit strange… Tested on TPS.

**Comment by viva-la-v** [comment]
Weird, for me it only pick up money, nothing else including ammo, eridium, health.

**Comment by 1basti1** [comment]
Oh good to know. I play in german

**Comment by viva-la-v** [comment]
Guys, I've solved it, please check this PR and use that version.
https://github.com/tominator1pl/bl-sdk-mods/pull/4

**Comment by viva-la-v** [comment]
> I discovered the bug, the "language", in my case I play in Spanish, so in addition to "Ammo" in the list (in the .py file of the mod) I added "Munición" and now it picks up the ammo.
> 
> You need to add the names of the objects in the list in several languages, maybe by request? otherwise it will only pick up the objects in the list as long as they have the same language name of the game.

Yes, it is because the `ItemName` is actually a localized string, so I use `GetFullDefinitionName()` instead, and replace the pickup dict with prefixes of full definition names.
Tested and works for me now.

**Comment by davoker** [comment]
> > I discovered the bug, the "language", in my case I play in Spanish, so in addition to "Ammo" in the list (in the .py file of the mod) I added "Munición" and now it picks up the ammo.
> > You need to add the names of the objects in the list in several languages, maybe by request? otherwise it will only pick up the objects in the list as long as they have the same language name of the game.
> 
> Yes, it is because the `ItemName` is actually a localized string, so I use `GetFullDefinitionName()` instead, and replace the pickup dict with prefixes of full definition names. Tested with BL2 and works fine for me now, not tested with TPS because I haven't played TPS yet.

Thanks for the fix =)

**Comment by tominator1pl** [comment]
Thanks for the help @viva-la-v
